services:
  - type: web
    name: friendship-proposal-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RAZORPAY_KEY_ID
        value: rzp_live_DUnhAJMFNwKiPz
      - key: RAZORPAY_KEY_SECRET
        value: mBeXJqyAFBic27YFkoT7oAC9
